export const buttonsList = [
    {type: 'action', value: 'C'},
    {type: 'oper', value: '( )'},
    {type: 'action', value: '√'},
    {type: 'oper', value: '÷'},
    {type: 'num', value: 7},
    {type: 'num', value: 8},
    {type: 'num', value: 9},
    {type: 'oper', value: '×'},
    {type: 'num', value: 4},
    {type: 'num', value: 5},
    {type: 'num', value: 6},
    {type: 'oper', value: '−'},
    {type: 'num', value: 1},
    {type: 'num', value: 2},
    {type: 'num', value: 3},
    {type: 'oper', value: '+'},
    {type: 'num', value: 0},
    {type: 'num', value: '.'},
    {type: 'action', value: '%'},
    {type: 'action', value: '='},
]
